name: Deploy (Tag)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          if [ -f constraints.txt ]; then
            python -m pip install -r requirements.txt -c constraints.txt
          else
            python -m pip install -r requirements.txt
          fi

      - name: Run smoke tests
        run: pytest -q -k "test_system or test_integration" --maxfail=1 --disable-warnings

      - name: Notify Streamlit Cloud (manual)
        run: |
          echo "Tag pushed. Please ensure Streamlit Cloud deploys from streamlit_app.py"
          echo "If using API or webhook for Streamlit Cloud, integrate here."

