[global]
developmentMode = false

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 1024

[browser]
gatherUsageStats = false

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s" 